services:
  postgres:
    container_name: 'postgres-db'
    image: 'postgres:latest'
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/register_service:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_DB=quickkick'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'